name: "Big testing"
on: 
  workflow_dispatch:

jobs:
  my-func:
    runs-on: ubuntu-latest
    steps:
    - uses: gauron99/knative-func-action@main
      with:
          version: 'knative-v1.18.0'
    - run: func version

