name: Go test with codecov

on: [pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Unit Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run test
        run: |
          cd testcodecov
          go test -race -cover -coverprofile=coverage.txt ./...
      - uses: codecov/codecov-action@v5
        with:
          # dont search for files, use precisely the specified ones below
          disable_search: true
          files: testcodecov/coverage.txt
          verbose: true

