name: testing knative hack dir thing

on: [workflow_dispatch,push]

jobs:
  update:
    name: Fetch me latest
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
    - name: Create PR
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: go run ./go-scripts/fetch-knative-latest.go

