name: testing knative hack dir thing

permissions:
  pull-requests: write

on: 
  workflow_dispatch:
  push:

jobs:
  update:
    name: Fetch me latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.23.4
    - name: Create PR
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        cd go-scripts && go run ./fetch-knative-hack.go

